# General info
title:            Charles Moulliard's blog
name:             Charles Moulliard's blog
description:      Apache PMC&Committer, Java Integration Geek, (Web)Technology advocate,</br> Photograph, Speaker, Mountain Biker, @RedHat
logo:             camel.jpg
disqus_shortname: cmoulliard
#Comment out url when working locally to resolve base urls correctly
url:              http://cmoulliard.github.io

display_content: false

# Owner/author information
owner:
  name:           Charles Moulliard
  avatar:         cmoulliard-devoxx.png
  email:          ch007m@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: cmoulliard       
  facebook: charles.moulliard      
  github: cmoulliard        
  stackexchange:  
  linkedin: charlesmoulliard       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/u/0/109261084728245345002

# Analytics and webmaster tools stuff goes here
google_analytics: UA-43962311-1

google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
# NOT USED
#  - title: Categories
#    url: /categories
#  - title: Search
#    url: /search
  - title: Tags
    url: /tags
  - title: RedHat
    url: http://redhat.com
    external: true
  - title: Talks
    url: /talks  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Brussels
# Allow to post blog in the future
future:      true

highlighter: rouge
# highlighter: pygmentize

# Rendering tool (rdiscount could also be used)
markdown:    kramdown

# Enable/Disable Google Search form in menu bar
google_search_form: true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Kramdown parameters
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  # use_coderay: false
  enable_coderay: false

 # Syntax highlighting with markdown
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]

#
# Gems required
#
# gems: ['jekyll-less','jekyll-sitemap']