source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-minibundle'
gem 'jekyll-less'
gem 'jekyll-sitemap'
gem 'jekyll-sass'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'coderay'
gem 'rake'
# gem 'thor'
gem 'activesupport'